services:
  postgres:
    image: postgres:16
    container_name: easykan-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: easykan-server
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: easykan-client
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    depends_on:
      - server

volumes:
  data:
