services:
  postgres:
    image: postgres:16
    container_name: easykan-postgres-dev
    environment:
      - POSTGRES_USER=easykan
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=easykan
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U easykan -d easykan"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: