spring:
  profiles:
    active: dev
  application:
    name: EasyKan
  datasource:
    url: jdbc:postgresql://localhost:5432/easykan
    username: easykan
    password: "passwd"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
